version: 2
    
jobs:
  deploydocs:
    branches:
      only:
        - master
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Deploy
          command: mkdocs gh-deploy
    
workflows:
  version: 2
  build:
    jobs:
      - deploydocs
